config/routes.rb
SimpleForum::Engine.routes.draw do

  root :to => 'forums#index', :via => :get

  resources :forums, :only => [:index, :show], :path => 'f' do
    resources :topics, :only => [:index, :show, :new, :create], :path => 't' do
      member do
        post :open
        post :close
      end

      resources :posts, :except => [:destroy], :path => 'p' do
        delete :delete, :on => :member
        get :preview, :on => :collection
      end
    end
  end

  namespace :admin do
    resources :forums do
      get :search_users, :on => :collection
    end
    resources :categories

  end

end

app/models/simple_forum.rb
module SimpleForum
  def self.table_name_prefix
    'simple_forum_'
  end
end

app/models/simple_forum/category.rb
module SimpleForum
  class Category < ::ActiveRecord::Base
    has_many :forums,
             :order => "#{SimpleForum::Forum.quoted_table_name}.position ASC",
             :dependent => :nullify,
             :class_name => "SimpleForum::Forum"


    scope :default_order, order("#{quoted_table_name}.position ASC")

    validates :name, :presence => true
    validates :position, :presence => true, :numericality => {:only_integer => true, :allow_nil => true}

    attr_accessible :name, :body, :position

    if respond_to?(:has_friendly_id)
      has_friendly_id :name, :use_slug => true, :approximate_ascii => true
    else
      def to_param
        "#{id}-#{name.to_s.parameterize}"
      end
    end

  end
end

app/models/simple_forum/forum.rb
module SimpleForum
  class Forum < ::ActiveRecord::Base
    #acts_as_nested_set

    has_many :topics,
             :order => "#{SimpleForum::Topic.quoted_table_name}.last_updated_at DESC",
             :dependent => :destroy,
             :class_name => "SimpleForum::Topic"

    belongs_to :recent_topic,
               :class_name => 'SimpleForum::Topic'

    has_many :posts,
             :order => "#{SimpleForum::Post.quoted_table_name}.created_at DESC",
             :class_name => 'SimpleForum::Post'

    belongs_to :recent_post,
               :class_name => 'SimpleForum::Post'

    belongs_to :category,
               :class_name => 'SimpleForum::Category'

    has_many :moderatorships,
             :class_name => 'SimpleForum::Moderatorship'

    has_many :moderators,
             :through => :moderatorships,
             :source => :user

    scope :default_order, order("#{quoted_table_name}.position ASC, #{quoted_table_name}.id ASC")

    validates :name, :presence => true
    validates :position, :presence => true, :numericality => {:only_integer => true, :allow_nil => true}

    attr_accessible :name, :body, :parent_id, :position, :moderator_ids, :category_id, :is_topicable

    if respond_to?(:has_friendly_id)
      has_friendly_id :name, :use_slug => true, :approximate_ascii => true
    else
      def to_param
        "#{id}-#{name.to_s.parameterize}"
      end
    end

    def moderated_by?(user)
      return false unless user
      @moderated_by_cache ||= {}
      if @moderated_by_cache.has_key?(user.id)
        @moderated_by_cache[user.id]
      else
        @moderated_by_cache[user.id] = moderators.include?(user)
      end
    end

    alias_method :is_moderator?, :moderated_by?

  end
end

app/models/simple_forum/moderatorship.rb
module SimpleForum
  class Moderatorship < ::ActiveRecord::Base
    belongs_to :forum,
               :class_name => "SimpleForum::Forum"

    belongs_to :user,
               :class_name => instance_eval(&SimpleForum.invoke(:user_class)).name

    validates :forum, :user, :presence => true
    validates :user_id, :uniqueness => {:scope => :forum_id, :allow_nil => true}

    attr_accessible :forum_id, :user_id

  end
end

app/controllers/simple_forum/admin/base_controller.rb
class SimpleForum::Admin::BaseController < ::SimpleForum::ApplicationController
  layout 'simple_forum/admin'
  before_filter :forum_admin_required

  protected

end

app/controllers/simple_forum/admin/categories_controller.rb
module SimpleForum
  module Admin
    class CategoriesController < ::SimpleForum::Admin::BaseController

      def index
        @categories = SimpleForum::Category.default_order.all

        respond_with(@categories)
      end

      def show

        respond_with([:admin, resource])
      end

      def edit

        respond_with([:admin, resource])
      end

      def new

        respond_with([:admin, resource])
      end

      def create
        success = resource.save

        respond_with([:admin, resource]) do |format|
          format.html do
            if success
              redirect_to [:admin, resource]
            else
              render :new
            end
          end
        end
      end

      def update
        success = resource.update_attributes(params[:category])

        respond_with([:admin, resource]) do |format|
          format.html do
            if success
              redirect_to [:admin, resource]
            else
              render :edit
            end
          end
        end
      end

      def destroy
        resource.destroy

        respond_with([:admin, resource])
      end

      private

      def resource
        @category ||= params[:id] ? SimpleForum::Category.find(params[:id]) : SimpleForum::Category.new(params[:category])
      end

      helper_method :resource

    end
  end
end

app/controllers/simple_forum/admin/forums_controller.rb
module SimpleForum
  module Admin
    class ForumsController < ::SimpleForum::Admin::BaseController

      def search_users
        user_class = instance_eval(&SimpleForum.invoke(:user_class))
        @users = user_class.where(["#{user_class.quoted_table_name}.email LIKE ?", "%#{params[:user_name_like].to_s.gsub(/[\%\_]/) { |m| "\\#{m}" }}%"]).limit(16)

        respond_to do |format|
          format.json do
            render :json => @users.inject({}) { |hash, u| hash[u.id] = u.name; hash }
          end
        end
      end

      def index
        @categories = SimpleForum::Category.default_order.includes({:forums => [{:recent_post => [:user, :topic]}, :moderators]})

        @forums = SimpleForum::Forum.default_order.includes({:recent_post => [:user, :topic]}, :moderators)
        @forums_by_category = @categories.inject(ActiveSupport::OrderedHash.new) { |h, c| h[c] = []; h }
        @forums.each do |f|
          (@forums_by_category[@categories.detect { |c| c.try(:id) == f.category_id }] ||= []) << f
        end
        @forums_by_category.reject! { |c, forums| forums.blank? }

        respond_with(@forums)
      end

      def show

        respond_with([:admin, resource])
      end

      def edit

        respond_with([:admin, resource])
      end

      def new

        respond_with([:admin, resource])
      end

      def create
        success = resource.save

        respond_with([:admin, resource]) do |format|
          format.html do
            if success
              redirect_to [:admin, resource]
            else
              render :new
            end
          end
        end
      end

      def update
        success = resource.update_attributes(params[:forum])

        respond_with([:admin, resource]) do |format|
          format.html do
            if success
              redirect_to [:admin, resource]
            else
              render :edit
            end
          end
        end
      end

      def destroy
        resource.destroy

        respond_with([:admin, resource])
      end

      private

      def resource
        @forum ||= params[:id] ? SimpleForum::Forum.find(params[:id]) : SimpleForum::Forum.new(params[:forum])
      end

      helper_method :resource

    end
  end
end

app/controllers/simple_forum/application_controller.rb
module SimpleForum
  class ApplicationController < ::ApplicationController #::ActionController::Base
    respond_to :html
    #protect_from_forgery

    layout SimpleForum.layout

    helper_method :authenticated_user, :user_authenticated?, :forum_admin?
    helper_method :simple_forum_recent_activity?

    private

    def authenticated_user
      instance_eval &SimpleForum.invoke(:authenticated_user)
    end

    def user_authenticated?
      instance_eval &SimpleForum.invoke(:user_authenticated?)
    end

    def authenticate_user
      redirect_to :back, :alert => t('simple_forum.controllers.you_have_to_be_signed_in_to_perform_this_action') unless user_authenticated?
    end

    def forum_admin?
      instance_eval(&SimpleForum.invoke(:forum_admin?))
    end

    def forum_admin_required
      redirect_to simple_forum.root_path unless forum_admin?
    end

    def simple_forum_activity_checker
      @_simple_forum_activity_checker ||= SimpleForum::UserActivity.recent_activity_for_user(authenticated_user)
    end

    def simple_forum_recent_activity?(forum_or_topic)
      return false unless user_authenticated?
      simple_forum_activity_checker.recent_activity?(forum_or_topic)
    end

    def bang_simple_forum_recent_activity(forum_or_topic)
      return unless user_authenticated?
      simple_forum_activity_checker.bang(forum_or_topic)
    end

  end
end

app/controllers/simple_forum/forums_controller.rb
module SimpleForum
  class ForumsController < ::SimpleForum::ApplicationController

    before_filter :find_forum, :except => [:index]

    def index
      @categories = SimpleForum::Category.default_order.includes({:forums => [{:recent_post => [:user, :topic]}, :moderators]})

      respond_to :html
    end

    def show
      bang_simple_forum_recent_activity(@forum)
      
      scope = @forum.topics.includes([:user, {:recent_post => :user}])
      @topics = scope.respond_to?(:paginate) ? scope.paginate(:page => params[:page], :per_page => params[:per_page]) : scope.all

      respond_to :html
    end

    private

    def find_forum
      @forum = SimpleForum::Forum.find params[:id]
    end

  end
end

app/controllers/simple_forum/posts_controller.rb
module SimpleForum
  class PostsController < ::SimpleForum::ApplicationController

    before_filter :authenticate_user, :except => [:index, :show]

    before_filter :find_forum
    before_filter :find_topic
    before_filter :find_post, :except => [:index, :new, :create, :preview]
    before_filter :build_post, :only => [:new, :create, :preview]
    before_filter :post_must_be_editable_by_authenticate_user, :only => [:edit, :update]

    def index

      respond_to do |format|
        format.html do
          redirect_to simple_forum.forum_topic_url(@forum, @topic), :status => :moved_permanently
        end
      end
    end

    def show

      respond_to do |format|
        format.html { redirect_to simple_forum.forum_topic_url(@forum, @topic, :page => @post.on_page, :anchor => "post-#{@post.id}") }
      end
    end

    def create
      success = @post.save

      respond_to do |format|
        format.html do
          if success
            redirect_to simple_forum.forum_topic_url(@forum, @topic, :page => @post.on_page, :anchor => "post-#{@post.id}"),
                        :notice => t('simple_forum.controllers.posts.post_created')
          else
            redirect_to simple_forum.forum_topic_url(@forum, @topic, :page => @topic.last_page, :anchor => (@topic.recent_post ? "post-#{@topic.recent_post.id}" : nil)),
                        :alert => @post.errors.full_messages.join(', ')
          end
        end
      end
    end

    def preview
      @post.created_at, @post.updated_at = Time.now

      respond_to do |format|
        format.js { render :partial => 'simple_forum/topics/post', :locals => {:post => @post, :preview => true} }
      end
    end

    def edit

      respond_to :html
    end

    def update
      @post.edited_by = authenticated_user
      @post.edited_at = Time.now
      success = @post.update_attributes(params[:post])

      respond_to do |format|
        format.html do
          if success
            redirect_to simple_forum.forum_topic_url(@forum, @topic, :page => @post.on_page, :anchor => "post-#{@post.id}"),
                        :notice => t('simple_forum.controllers.posts.post_updated')
          else
            redirect_to :back, :alert => @post.errors.full_messages.join(', ')
          end
        end
      end
    end


    def delete
      success = @post.mark_as_deleted_by(authenticated_user) #check if post is deletable by authenticated_user in mark_as_deleted_by method

      respond_to do |format|
        format.html do
          if success
            redirect_to :back, :notice => t('simple_forum.controllers.posts.post_deleted')
          else
            redirect_to :back, :alert => t('simple_forum.controllers.posts.post_cant_be_deleted')
          end
        end
      end
    end

    private

    def find_forum
      @forum = SimpleForum::Forum.find params[:forum_id]
    end

    def find_topic
      @topic = @forum.topics.find params[:topic_id]
    end

    def find_post
      @post = @topic.posts.find params[:id]
    end

    def build_post
      @post = @topic.posts.new params[:post] do |post|
        post.user = authenticated_user
      end
    end

    def post_must_be_editable_by_authenticate_user
      redirect_to :back, :alert => t('simple_forum.controllers.posts.post_cant_be_edited') unless @post.editable_by?(authenticated_user, nil)
    end

  end
end

app/controllers/simple_forum/topics_controller.rb
module SimpleForum
  class TopicsController < ::SimpleForum::ApplicationController
    respond_to :html

    before_filter :authenticate_user, :only => [:new, :create, :open, :close]

    before_filter :find_forum
    before_filter :find_topic, :except => [:index, :new, :create]
    before_filter :build_topic, :only => [:new, :create]

    before_filter :moderator_required, :only => [:open, :close]

    def index

      respond_to do |format|
        format.html do
          redirect_to simple_forum.forum_url(@forum), :status => :moved_permanently
        end
      end
    end

    def show
      bang_simple_forum_recent_activity(@topic)
      @topic.increment_views_count

      @posts_search = @topic.posts.includes([:user, :deleted_by, :edited_by])
      @posts = @posts_search.respond_to?(:paginate) ?
          @posts_search.paginate(:page => params[:page], :per_page => params[:per_page] || SimpleForum::Post.per_page) :
          @posts_search.all

      @post = SimpleForum::Post.new

      respond_with(@topic)
    end

    def new

      respond_with(@topic)
    end

    def create
      success = @topic.save

      respond_to do |format|
        format.html do
          if success
            flash[:notice] = t('simple_forum.controllers.topics.topic_created')
            redirect_to simple_forum.forum_topic_url(@forum, @topic)
          else
            flash.now[:alert] = @topic.errors.full_messages.join(' ')
            render :new
          end
        end
      end
    end

    def open
      success = if @topic.is_open?
                  false
                else
                  @topic.open!
                  true
                end

      respond_to do |format|
        format.html do
          if success
            redirect_to :back, :notice => t('simple_forum.controllers.topics.topic_opened')
          else
            redirect_to :back, :alert => t('simple_forum.controllers.topics.topic_already_opened')
          end
        end
      end
    end

    def close
      success = if @topic.is_open?
                  @topic.close!
                  true
                else
                  false
                end

      respond_to do |format|
        format.html do
          if success
            redirect_to :back, :notice => t('simple_forum.controllers.topics.topic_closed')
          else
            redirect_to :back, :alert => t('simple_forum.controllers.topics.topic_already_closed')
          end
        end
      end
    end

    private

    def find_forum
      @forum = SimpleForum::Forum.find params[:forum_id]
    end

    def find_topic
      @topic = @forum.topics.find params[:id]
    end

    def build_topic
      @topic = @forum.topics.new params[:topic] do |topic|
        topic.user = authenticated_user
      end
    end

    def moderator_required
      redirect_to :back, :alert => t('simple_forum.controllers.you_are_not_permitted_to_perform_this_action') unless @forum.moderated_by?(authenticated_user)
    end

  end
end

app/views/simple_forum/topics/_post.html.erb
<tr id="<%= "post-#{post.id}" %>" class="<%= local_assigns[:preview] ? 'preview' : nil %>">
  <td class="user-cell">
          <span class="name">
            <strong><%= post.user.name %></strong>
          </span>
    <br/>
          <span class="postdetails">
            <%= t('.user_joined') %>:
            <%= l post.user.created_at.to_date %>
            <br/>
            <% if post.user.respond_to?(:forum_posts_count) %>
              <%= t('.user_posts_count') %>:
                <%= number_with_delimiter post.user.forum_posts_count %>
            <% end %>
          </span>
  </td>
  <td>
    <span style="display: none;"><a name="<%= post.id %>"></a></span>
    <table class="user-post" cellpadding="6" cellspacing="6" style="width: 100%;">
      <tr class="post-header">
        <td style="width: 40%;">
          <%= t('.post_sent') %>:
          <%= l post.created_at %>
          /
          <%= "#{time_ago_in_words(post.created_at)} #{t('simple_forum.ago', :default => 'ago')}" %>
        </td>
        <td class="actions">
          <% if user_authenticated? %>
              <% if post.editable_by?(authenticated_user, @forum.moderated_by?(authenticated_user)) %>
                  <%= link_to t('.edit'), simple_forum.edit_forum_topic_post_path(@forum, @topic, post) %>
              <% end %>
              <% if post.deletable_by?(authenticated_user, @forum.moderated_by?(authenticated_user)) %>
                  <%= link_to t('.delete'), simple_forum.delete_forum_topic_post_path(@forum, @topic, post), :method => :delete, :confirm => t('simple_forum.are_you_sure', :default => 'Are you sure?') %>
              <% end %>
              <% if @topic.is_open? && !post.is_deleted? %>
                  <%= link_to t('.cite'), "#new_post_form", :onclick => "$('#new_post_form textarea').val('#{escape_javascript("[quote=\"#{post.user.name}\"]\n#{post.body}\n[/quote]")}'); return false;", :class => 'cite-post' %>
              <% end %>
          <% end %>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <div class="postbody">
            <% if post.is_deleted? %>
                <div class='post-deleted'>
                  <%= t('.post_deleted') %>
                  <% if post.deleted_by %>
                      <%= t('simple_forum.by') %>
                      <%= post.deleted_by.name %>
                  <% end %>
                  <%= t('simple_forum.at') %>
                  <%= l post.deleted_at %>
                </div>
            <% else %>
                <%= post.output %>
            <% end %>
            <% if !post.is_deleted? && post.is_edited? %>
                <div class="post-edited">
                  <%= t('.post_edited') %>
                  <% if post.edited_by %>
                      <%= t('simple_forum.by') %>
                      <%= post.edited_by.name %>
                  <% end %>
                  <%= t('simple_forum.at') %>
                  <%= l post.edited_at %>
                </div>
            <% end %>
          </div>
        </td>
      </tr>
    </table>
  </td>
</tr>

app/views/simple_forum/topics/new.html.erb
<div id="breadcrumbs">
  <%= link_to SimpleForum.main_application_name, main_app.root_path %>
  &gt;
  <%= link_to 'Forum', simple_forum.root_path %>
  &gt;
  <%= link_to @forum.name, simple_forum.forum_path(@forum) %>
  &gt;
  <%= t('.new_topic') %>
</div>

<%= form_for @topic, :as => :topic, :url => simple_forum.forum_topics_path(@forum) do |f| %>
    <p>
      <%= f.label :title %><br/>
      <%= f.text_field :title %>
    </p>
    <p>
      <%= f.label :body %><br/>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/simple_forum/topics/show.html.erb
<% content_for :stylesheets, stylesheet_link_tag('simple_forum/markitup') %>
<% content_for :javascripts, javascript_include_tag("simple_forum/markitup") %>

<% content_for :head do %>
    <script type="text/javascript">
        var post_preview_path = "<%= simple_forum.preview_forum_topic_posts_path(@forum, @topic) %>";
    </script>
<% end %>

<div id="breadcrumbs">
  <%= link_to SimpleForum.main_application_name, main_app.root_path %>
  &gt;
  <%= link_to 'Forum', simple_forum.root_path %>
  &gt;
  <%= link_to @forum.name, simple_forum.forum_path(@forum) %>
  &gt;
  <%= @topic.title %>
</div>

<% content_for :left_sidebar do %>
    <ul>
      <% if user_authenticated? && @forum.is_moderator?(authenticated_user) %>
          <li>
            <% if @topic.is_open? %>
                <%= link_to t('.close_topic'), simple_forum.close_forum_topic_path(@forum, @topic), :method => :post, :confirm => t('simple_forum.are_you_sure', :default => 'Are you sure?') %>
            <% else %>
                <%= link_to t('.open_topic'), simple_forum.open_forum_topic_path(@forum, @topic), :method => :post, :confirm => t('simple_forum.are_you_sure', :default => 'Are you sure?') %>
            <% end %>
          </li>
      <% end %>
    </ul>
<% end %>

<table class="topic-table forum-table" cellpadding="6" cellspacing="6">
  <% for post in @posts do -%>
      <%= render :partial => 'post', :locals => {:post => post} %>
  <% end %>
</table>

<%= will_paginate @posts if respond_to?(:will_paginate) %>

<% if @topic.is_open? %>
    <% if user_authenticated? %>
        <%= form_for @post, :url => simple_forum.forum_topic_posts_path(@forum, @topic), :as => :post, :html => {:id => 'new_post_form'} do |f| -%>
            <p>
              <%= f.label :body %>
              <%= f.text_area :body, :class => 'markitup post-body' %>
            </p>

            <p>
              <%= f.submit %>
            </p>
        <% end %>
    <% else %>
        <%= t('.you_have_to_be_signed_in_to_create_post') %>
    <% end %>
<% else %>
    <p>
      <%= t('.topic_is_closed') %>
    </p>
<% end %>